; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = src

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_speed = 115200
monitor_filters = send_on_enter, time
lib_extra_dirs = lib
lib_deps =
	SoftwareSerial  ; https://platformio.org/lib/show/1/SoftwareSerial
build_src_filter =
	+<uno/*>
	-<esp32/*>
	-<../legacy_ino/*>

[env:unoHome]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600
upload_speed = 115200
upload_resetmethod = nodetach
monitor_filters = send_on_enter, time
lib_extra_dirs = lib
build_src_filter =
	+<uno/*>
	-<esp32/*>
	-<../legacy_ino/*>

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = 
	+<esp32/*>
	-<uno/*>
	-<../legacy_ino/*>

[env:esp32vn-iot-uno]
platform = espressif32
board = esp32vn-iot-uno
framework = arduino
